version: "3.8"
services:
  myflix-ui:
    build: myflix-ui
    container_name: myflix-ui_c

    ports:

     - '4000:4000'


  myflix-api:
    build: myflix-api
    container_name: myflix-api_c

    ports:
      - "5000:5000"
    links:
      - mongo 
  mongo:
    image: mongo 
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    

